# Simple Azure Pipeline Example for Self-Hosted Agent
# Save this as: .azure-pipelines.yml

trigger:
- main   # pipeline will trigger on every push to the main branch

pool:
  name: SelfHostedPool   # 🔹 change this to your self-hosted pool name

steps:
# 1️⃣ Checkout your code
- checkout: self
  displayName: 'Checkout source code'

# 2️⃣ Print basic info
- script: |
    echo "Agent name: $(Agent.Name)"
    echo "Running on: $(Agent.OS)"
    echo "Working directory: $(System.DefaultWorkingDirectory)"
  displayName: 'Show environment info'

# 3️⃣ Install dependencies (for Node.js example)
- script: |
    echo "Installing npm dependencies..."
    npm install
  displayName: 'Install dependencies'

# 4️⃣ Build project
- script: |
    echo "Building project..."
    npm run build || echo "Build step skipped (no build script defined)"
  displayName: 'Build project'

# 5️⃣ Run tests (optional)
- script: |
    echo "Running tests..."
    npm test || echo "No tests defined"
  displayName: 'Run tests'

# 6️⃣ Finish
- script: echo "✅ Pipeline completed successfully!"
  displayName: 'Finish'
